# **Part 1**

Load the Dataset

In [52]:
# importing pandas module as pd (shortform) and then using read_csv function to read the csv from its file path
import pandas as pd

data = pd.read_csv('/content/sample_data/california_housing_train.csv')
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

Data Summary

In [53]:
# using describe function to find all stats for each column with numerical data
data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [54]:
# using loop i check for values and add it in the list, if its already present then it does nothing and moves ahead
list = []
for i in range (0,17000):
  n = data['total_bedrooms'][i]
  if n in list:
    pass
  else:
    list.append(n)

print(list)
print("Distinct values of total_bedrooms: ",len(list))

[1283.0, 1901.0, 174.0, 337.0, 326.0, 236.0, 680.0, 168.0, 1175.0, 309.0, 801.0, 483.0, 248.0, 464.0, 378.0, 587.0, 322.0, 33.0, 386.0, 24.0, 360.0, 243.0, 95.0, 129.0, 397.0, 139.0, 270.0, 191.0, 294.0, 394.0, 262.0, 196.0, 171.0, 113.0, 220.0, 373.0, 246.0, 666.0, 104.0, 389.0, 440.0, 573.0, 72.0, 913.0, 492.0, 523.0, 218.0, 287.0, 610.0, 136.0, 283.0, 382.0, 366.0, 387.0, 275.0, 581.0, 199.0, 634.0, 340.0, 545.0, 325.0, 268.0, 395.0, 454.0, 403.0, 365.0, 530.0, 316.0, 142.0, 221.0, 162.0, 606.0, 480.0, 416.0, 375.0, 328.0, 835.0, 438.0, 490.0, 202.0, 217.0, 269.0, 256.0, 301.0, 289.0, 594.0, 208.0, 235.0, 279.0, 282.0, 143.0, 203.0, 507.0, 414.0, 274.0, 307.0, 177.0, 187.0, 317.0, 244.0, 231.0, 99.0, 238.0, 448.0, 103.0, 81.0, 18.0, 379.0, 1257.0, 49.0, 272.0, 43.0, 25.0, 46.0, 536.0, 57.0, 280.0, 958.0, 515.0, 97.0, 65.0, 94.0, 290.0, 2331.0, 89.0, 1997.0, 354.0, 820.0, 1228.0, 705.0, 54.0, 499.0, 277.0, 800.0, 512.0, 19.0, 654.0, 476.0, 625.0, 273.0, 409.0, 192.0, 714.0, 787.0, 176.0, 295.0, 468.0, 858.0, 352.0, 258.0, 849.0, 1326.0, 1349.0, 566.0, 1039.0, 2224.0, 91.0, 444.0, 1222.0, 284.0, 109.0, 2555.0, 760.0, 481.0, 556.0, 410.0, 851.0, 831.0, 487.0, 861.0, 367.0, 411.0, 3923.0, 2000.0, 514.0, 406.0, 3098.0, 1859.0, 1542.0, 1152.0, 1238.0, 348.0, 3479.0, 2405.0, 2460.0, 1149.0, 2257.0, 1618.0, 2007.0, 1089.0, 872.0, 500.0, 893.0, 1260.0, 2837.0, 782.0, 48.0, 1296.0, 1343.0, 361.0, 1303.0, 1266.0, 1110.0, 249.0, 1206.0, 992.0, 643.0, 920.0, 745.0, 1234.0, 471.0, 1512.0, 2481.0, 441.0, 2020.0, 636.0, 1875.0, 868.0, 1882.0, 85.0, 1229.0, 1074.0, 713.0, 2634.0, 1395.0, 780.0, 306.0, 754.0, 1444.0, 859.0, 2315.0, 852.0, 648.0, 763.0, 2186.0, 1839.0, 463.0, 1714.0, 1217.0, 1387.0, 1780.0, 562.0, 1529.0, 399.0, 1743.0, 67.0, 166.0, 1652.0, 82.0, 876.0, 827.0, 538.0, 1719.0, 847.0, 157.0, 74.0, 711.0, 374.0, 875.0, 682.0, 661.0, 946.0, 1070.0, 845.0, 10.0, 702.0, 751.0, 525.0, 1946.0, 68.0, 786.0, 520.0, 63.0, 565.0, 1527.0, 1985.0, 495.0, 855.0, 219.0, 532.0, 792.0, 1030.0, 770.0, 938.0, 131.0, 118.0, 443.0, 1689.0, 921.0, 291.0, 906.0, 812.0, 761.0, 265.0, 321.0, 491.0, 198.0, 796.0, 259.0, 777.0, 429.0, 623.0, 1583.0, 541.0, 916.0, 621.0, 501.0, 333.0, 593.0, 393.0, 102.0, 840.0, 672.0, 738.0, 426.0, 149.0, 773.0, 552.0, 810.0, 737.0, 100.0, 2127.0, 1164.0, 597.0, 628.0, 838.0, 703.0, 898.0, 424.0, 637.0, 511.0, 624.0, 834.0, 494.0, 752.0, 1594.0, 1148.0, 670.0, 990.0, 895.0, 278.0, 466.0, 1258.0, 699.0, 1401.0, 2630.0, 1410.0, 445.0, 381.0, 253.0, 285.0, 729.0, 2292.0, 2656.0, 2479.0, 974.0, 2205.0, 804.0, 1702.0, 1096.0, 431.0, 405.0, 178.0, 639.0, 353.0, 245.0, 2506.0, 592.0, 1434.0, 293.0, 599.0, 3093.0, 421.0, 857.0, 467.0, 497.0, 691.0, 757.0, 755.0, 973.0, 740.0, 496.0, 1796.0, 638.0, 803.0, 1094.0, 266.0, 693.0, 1325.0, 630.0, 632.0, 722.0, 32.0, 1018.0, 338.0, 1101.0, 1413.0, 313.0, 583.0, 1344.0, 2833.0, 449.0, 125.0, 312.0, 640.0, 498.0, 83.0, 472.0, 1309.0, 1062.0, 1279.0, 341.0, 1423.0, 1029.0, 662.0, 447.0, 369.0, 147.0, 537.0, 158.0, 577.0, 1165.0, 1036.0, 658.0, 69.0, 1704.0, 2401.0, 3474.0, 866.0, 949.0, 758.0, 1521.0, 163.0, 334.0, 611.0, 547.0, 339.0, 130.0, 216.0, 164.0, 582.0, 622.0, 1292.0, 1979.0, 319.0, 401.0, 943.0, 555.0, 519.0, 891.0, 886.0, 567.0, 430.0, 3280.0, 645.0, 618.0, 479.0, 210.0, 663.0, 815.0, 723.0, 608.0, 824.0, 706.0, 734.0, 692.0, 398.0, 1368.0, 976.0, 239.0, 351.0, 1335.0, 750.0, 1579.0, 673.0, 370.0, 384.0, 708.0, 488.0, 772.0, 963.0, 865.0, 516.0, 675.0, 184.0, 41.0, 335.0, 407.0, 664.0, 11.0, 209.0, 446.0, 698.0, 775.0, 383.0, 513.0, 428.0, 1492.0, 1655.0, 150.0, 391.0, 455.0, 627.0, 572.0, 818.0, 148.0, 735.0, 795.0, 1213.0, 781.0, 2888.0, 435.0, 107.0, 1418.0, 1256.0, 826.0, 345.0, 350.0, 1881.0, 665.0, 557.0, 418.0, 785.0, 955.0, 991.0, 860.0, 425.0, 357.0, 683.0, 542.0, 422.0, 356.0, 1461.0, 846.0, 297.0, 260.0, 766.0, 646.0, 1205.0, 569.0, 1166.0, 390.0, 2035.0, 372.0, 642.0, 1293.0, 254.0, 121.0, 588.0, 1436.0, 1091.0, 731.0, 292.0, 250.0, 308.0, 359.0, 344.0, 408.0, 388.0, 612.0, 617.0, 580.0, 343.0, 686.0, 286.0, 929.0, 563.0, 320.0, 233.0, 809.0, 2114.0, 1276.0, 255.0, 190.0, 417.0, 877.0, 550.0, 332.0, 288.0, 419.0, 619.0, 111.0, 667.0, 234.0, 742.0, 1015.0, 205.0, 679.0, 311.0, 925.0, 940.0, 1047.0, 960.0, 522.0, 165.0, 1632.0, 927.0, 473.0, 1237.0, 578.0, 1231.0, 977.0, 1866.0, 349.0, 240.0, 614.0, 228.0, 749.0, 549.0, 656.0, 652.0, 475.0, 823.0, 456.0, 267.0, 725.0, 1025.0, 774.0, 1173.0, 1331.0, 551.0, 571.0, 2628.0, 324.0, 585.0, 347.0, 450.0, 931.0, 3336.0, 2490.0, 2352.0, 856.0, 155.0, 596.0, 508.0, 598.0, 615.0, 1078.0, 764.0, 603.0, 712.0, 533.0, 793.0, 559.0, 427.0, 506.0, 1381.0, 52.0, 477.0, 327.0, 1271.0, 1442.0, 539.0, 1185.0, 152.0, 534.0, 214.0, 546.0, 376.0, 503.0, 779.0, 945.0, 653.0, 206.0, 985.0, 323.0, 862.0, 651.0, 161.0, 364.0, 368.0, 1044.0, 412.0, 685.0, 2576.0, 342.0, 2613.0, 744.0, 474.0, 609.0, 799.0, 548.0, 601.0, 704.0, 247.0, 137.0, 1195.0, 911.0, 224.0, 553.0, 560.0, 460.0, 591.0, 377.0, 371.0, 1299.0, 1035.0, 919.0, 1407.0, 13.0, 242.0, 629.0, 892.0, 586.0, 771.0, 518.0, 830.0, 355.0, 600.0, 616.0, 182.0, 469.0, 478.0, 644.0, 457.0, 502.0, 159.0, 14.0, 71.0, 146.0, 509.0, 55.0, 4957.0, 1572.0, 961.0, 937.0, 363.0, 817.0, 717.0, 462.0, 413.0, 633.0, 724.0, 1285.0, 331.0, 101.0, 237.0, 77.0, 669.0, 271.0, 510.0, 825.0, 315.0, 241.0, 257.0, 579.0, 554.0, 650.0, 461.0, 695.0, 732.0, 1031.0, 671.0, 1182.0, 602.0, 768.0, 415.0, 720.0, 504.0, 423.0, 314.0, 180.0, 230.0, 392.0, 1157.0, 437.0, 120.0, 828.0, 1051.0, 829.0, 1032.0, 1603.0, 595.0, 710.0, 212.0, 493.0, 681.0, 756.0, 329.0, 1816.0, 132.0, 458.0, 330.0, 701.0, 1265.0, 459.0, 962.0, 2279.0, 402.0, 303.0, 261.0, 631.0, 489.0, 674.0, 821.0, 867.0, 607.0, 183.0, 172.0, 1621.0, 993.0, 3245.0, 1000.0, 1952.0, 1100.0, 79.0, 765.0, 558.0, 1593.0, 604.0, 486.0, 942.0, 753.0, 2248.0, 1235.0, 700.0, 12.0, 1187.0, 115.0, 647.0, 305.0, 1176.0, 806.0, 1168.0, 181.0, 897.0, 802.0, 1424.0, 87.0, 42.0, 1683.0, 2688.0, 575.0, 1509.0, 1104.0, 225.0, 997.0, 716.0, 1147.0, 1559.0, 432.0, 124.0, 3366.0, 1037.0, 728.0, 833.0, 794.0, 175.0, 5.0, 213.0, 850.0, 953.0, 1584.0, 1455.0, 1665.0, 251.0, 524.0, 222.0, 1073.0, 1079.0, 1196.0, 864.0, 1617.0, 1095.0, 912.0, 229.0, 304.0, 1385.0, 2537.0, 1240.0, 1468.0, 805.0, 1758.0, 1324.0, 954.0, 689.0, 433.0, 988.0, 873.0, 2495.0, 910.0, 1330.0, 1026.0, 2865.0, 7.0, 482.0, 362.0, 848.0, 1008.0, 807.0, 727.0, 135.0, 1111.0, 185.0, 112.0, 173.0, 521.0, 1093.0, 1361.0, 2696.0, 2031.0, 759.0, 2269.0, 657.0, 108.0, 918.0, 1245.0, 797.0, 310.0, 1118.0, 201.0, 1379.0, 442.0, 626.0, 882.0, 1042.0, 380.0, 641.0, 605.0, 1156.0, 1108.0, 1063.0, 2208.0, 1914.0, 543.0, 1437.0, 465.0, 1448.0, 743.0, 659.0, 300.0, 484.0, 690.0, 526.0, 844.0, 747.0, 922.0, 814.0, 346.0, 264.0, 1227.0, 385.0, 276.0, 1005.0, 979.0, 1121.0, 1244.0, 3.0, 676.0, 687.0, 684.0, 134.0, 1514.0, 1744.0, 4072.0, 890.0, 3933.0, 996.0, 733.0, 808.0, 193.0, 884.0, 888.0, 822.0, 841.0, 1371.0, 928.0, 660.0, 540.0, 1112.0, 1636.0, 1380.0, 528.0, 715.0, 677.0, 1525.0, 3032.0, 2726.0, 105.0, 1273.0, 791.0, 2988.0, 1533.0, 527.0, 299.0, 1172.0, 1043.0, 1307.0, 2111.0, 678.0, 169.0, 3753.0, 263.0, 1703.0, 59.0, 887.0, 1287.0, 574.0, 302.0, 160.0, 138.0, 133.0, 1523.0, 420.0, 232.0, 2212.0, 1140.0, 123.0, 1842.0, 1003.0, 881.0, 2041.0, 2445.0, 64.0, 4952.0, 1298.0, 1372.0, 2181.0, 1605.0, 889.0, 1224.0, 769.0, 28.0, 1242.0, 1535.0, 1341.0, 2549.0, 531.0, 1832.0, 453.0, 813.0, 1153.0, 1747.0, 470.0, 568.0, 404.0, 9.0, 44.0, 697.0, 296.0, 1269.0, 1274.0, 122.0, 45.0, 1493.0, 1208.0, 1139.0, 2306.0, 1145.0, 1373.0, 1295.0, 211.0, 1864.0, 298.0, 1125.0, 668.0, 1550.0, 1081.0, 1360.0, 2043.0, 4819.0, 1071.0, 570.0, 2511.0, 718.0, 1137.0, 400.0, 1517.0, 22.0, 452.0, 1017.0, 1316.0, 869.0, 1320.0, 226.0, 620.0, 880.0, 1767.0, 227.0, 1913.0, 1249.0, 336.0, 1799.0, 1170.0, 576.0, 2238.0, 1802.0, 649.0, 1470.0, 153.0, 746.0, 62.0, 1486.0, 2057.0, 3217.0, 34.0, 215.0, 1200.0, 2819.0, 29.0, 926.0, 934.0, 439.0, 76.0, 1210.0, 73.0, 1066.0, 127.0, 1311.0, 396.0, 156.0, 517.0, 1745.0, 1092.0, 1516.0, 2640.0, 1181.0, 3915.0, 47.0, 1491.0, 959.0, 1193.0, 2485.0, 1386.0, 4095.0, 1687.0, 1599.0, 811.0, 1306.0, 1209.0, 816.0, 1088.0, 1054.0, 544.0, 930.0, 1366.0, 970.0, 56.0, 281.0, 252.0, 903.0, 188.0, 1275.0, 564.0, 1138.0, 932.0, 485.0, 200.0, 590.0, 952.0, 1119.0, 871.0, 1364.0, 589.0, 721.0, 61.0, 189.0, 1555.0, 1453.0, 154.0, 1011.0, 778.0, 145.0, 1333.0, 51.0, 1717.0, 2370.0, 1893.0, 2278.0, 726.0, 2062.0, 1261.0, 894.0, 1069.0, 1748.0, 5471.0, 998.0, 2174.0, 194.0, 6.0, 318.0, 358.0, 92.0, 3522.0, 1544.0, 2274.0, 1004.0, 70.0, 1268.0, 561.0, 584.0, 1068.0, 80.0, 223.0, 1161.0, 5290.0, 901.0, 2.0, 2862.0, 1351.0, 1620.0, 451.0, 1098.0, 1178.0, 986.0, 1281.0, 707.0, 2474.0, 1642.0, 1155.0, 1345.0, 975.0, 923.0, 535.0, 1459.0, 1978.0, 1650.0, 2751.0, 3078.0, 1449.0, 853.0, 1174.0, 1623.0, 1597.0, 1251.0, 694.0, 1624.0, 1129.0, 434.0, 78.0, 1659.0, 944.0, 655.0, 1065.0, 767.0, 870.0, 1204.0, 741.0, 197.0, 2812.0, 151.0, 1363.0, 4179.0, 114.0, 1077.0, 790.0, 1538.0, 1124.0, 1332.0, 1086.0, 3079.0, 88.0, 2289.0, 1055.0, 967.0, 1575.0, 505.0, 2185.0, 2486.0, 1789.0, 2283.0, 1255.0, 1191.0, 116.0, 117.0, 1675.0, 1159.0, 98.0, 1761.0, 1384.0, 1398.0, 1569.0, 1189.0, 965.0, 783.0, 2276.0, 1526.0, 207.0, 30.0, 2919.0, 86.0, 969.0, 1679.0, 1060.0, 2005.0, 128.0, 688.0, 836.0, 719.0, 1546.0, 144.0, 2602.0, 1426.0, 883.0, 1715.0, 924.0, 1547.0, 904.0, 613.0, 529.0, 709.0, 1027.0, 905.0, 879.0, 964.0, 982.0, 1338.0, 1289.0, 106.0, 1782.0, 179.0, 878.0, 971.0, 635.0, 908.0, 1056.0, 696.0, 1144.0, 1020.0, 1045.0, 170.0, 1154.0, 436.0, 1485.0, 1615.0, 1374.0, 1083.0, 1264.0, 1357.0, 1706.0, 1578.0, 1141.0, 995.0, 1117.0, 832.0, 195.0, 957.0, 31.0, 854.0, 914.0, 1048.0, 1422.0, 1075.0, 8.0, 935.0, 2873.0, 1454.0, 1821.0, 1061.0, 58.0, 1146.0, 736.0, 204.0, 4171.0, 1532.0, 1369.0, 1105.0, 1508.0, 819.0, 1647.0, 4335.0, 956.0, 1221.0, 186.0, 907.0, 1847.0, 885.0, 1614.0, 839.0, 1628.0, 1960.0, 1034.0, 1494.0, 1186.0, 1024.0, 1797.0, 739.0, 1892.0, 2823.0, 1013.0, 1127.0, 1007.0, 1136.0, 1773.0, 167.0, 2953.0, 1513.0, 1067.0, 1097.0, 1133.0, 896.0, 1211.0, 900.0, 1549.0, 789.0, 1663.0, 1180.0, 1085.0, 1301.0, 1059.0, 1262.0, 899.0, 1877.0, 1464.0, 1253.0, 1822.0, 1504.0, 748.0, 1359.0, 994.0, 1503.0, 1197.0, 119.0, 968.0, 16.0, 2145.0, 788.0, 981.0, 75.0, 1489.0, 60.0, 1465.0, 1488.0, 26.0, 20.0, 1021.0, 1367.0, 1856.0, 1131.0, 1420.0, 1438.0, 1944.0, 2077.0, 1417.0, 90.0, 776.0, 1130.0, 730.0, 140.0, 1277.0, 902.0, 3179.0, 1116.0, 1114.0, 1707.0, 1012.0, 2293.0, 1252.0, 1661.0, 917.0, 1016.0, 1169.0, 874.0, 1980.0, 2961.0, 1215.0, 1190.0, 2610.0, 2530.0, 1203.0, 1490.0, 762.0, 36.0, 1716.0, 1132.0, 2158.0, 1033.0, 141.0, 1263.0, 2055.0, 1248.0, 1084.0, 1450.0, 1171.0, 1183.0, 1634.0, 1188.0, 1646.0, 1290.0, 1102.0, 1134.0, 3335.0, 1984.0, 2679.0, 1482.0, 1763.0, 1452.0, 1057.0, 1404.0, 1023.0, 3638.0, 1626.0, 1653.0, 1050.0, 1803.0, 2793.0, 1038.0, 2154.0, 1576.0, 1328.0, 3680.0, 1710.0, 798.0, 3170.0, 2022.0, 2866.0, 1319.0, 1560.0, 1827.0, 1202.0, 1781.0, 1729.0, 23.0, 2437.0, 1312.0, 1158.0, 2075.0, 3039.0, 1537.0, 1028.0, 989.0, 1611.0, 126.0, 1214.0, 1480.0, 1548.0, 909.0, 1365.0, 84.0, 2211.0, 1394.0, 1192.0, 1472.0, 1040.0, 1126.0, 966.0, 2604.0, 4386.0, 1440.0, 1963.0, 1590.0, 3984.0, 1286.0, 1477.0, 950.0, 1457.0, 1076.0, 1695.0, 2574.0, 2193.0, 1150.0, 2038.0, 1358.0, 842.0, 1321.0, 1010.0, 4798.0, 1499.0, 2814.0, 1768.0, 1350.0, 1820.0, 1737.0, 2138.0, 1151.0, 1002.0, 2473.0, 987.0, 2717.0, 1143.0, 1473.0, 784.0, 1657.0, 1409.0, 1872.0, 951.0, 1784.0, 1995.0, 2527.0, 1557.0, 2139.0, 1664.0, 4457.0, 1755.0, 984.0, 1976.0, 1412.0, 999.0, 1826.0, 1994.0, 2366.0, 3945.0, 1317.0, 1239.0, 1082.0, 1322.0, 1858.0, 3224.0, 1849.0, 1869.0, 1142.0, 2387.0, 2691.0, 2355.0, 2560.0, 941.0, 4183.0, 1506.0, 1692.0, 2206.0, 17.0, 40.0, 1300.0, 4407.0, 2704.0, 2309.0, 4093.0, 2222.0, 110.0, 1730.0, 1058.0, 2611.0, 3521.0, 1233.0, 2924.0, 1573.0, 1049.0, 2685.0, 2141.0, 35.0, 1600.0, 38.0, 1539.0, 1220.0, 37.0, 1769.0, 1397.0, 1765.0, 2418.0, 2131.0, 1705.0, 863.0, 1670.0, 1370.0, 939.0, 1551.0, 2121.0, 947.0, 1250.0, 837.0, 1429.0, 1346.0, 1313.0, 39.0, 1439.0, 93.0, 1382.0, 53.0, 1080.0, 1545.0, 2453.0, 1756.0, 1831.0, 1216.0, 3114.0, 1184.0, 1475.0, 1288.0, 1666.0, 96.0, 4.0, 1871.0, 1348.0, 2424.0, 978.0, 1673.0, 1006.0, 1046.0, 1906.0, 1355.0, 1639.0, 1416.0, 1284.0, 50.0, 1019.0, 1278.0, 1643.0, 1314.0, 1739.0, 1246.0, 2690.0, 1774.0, 27.0, 1099.0, 1106.0, 1819.0, 2372.0, 1558.0, 1777.0, 1090.0, 21.0, 3559.0, 1411.0, 3513.0, 2979.0, 3358.0, 1507.0, 2282.0, 1487.0, 3392.0, 1446.0, 3630.0, 1992.0, 1433.0, 1606.0, 2617.0, 2996.0, 3457.0, 1456.0, 1241.0, 1087.0, 66.0, 1103.0, 2011.0, 4492.0, 1522.0, 2220.0, 3008.0, 1857.0, 1878.0, 2546.0, 1052.0, 2210.0, 6445.0, 1957.0, 1375.0, 1921.0, 843.0, 1232.0, 1163.0, 1895.0, 2074.0, 1201.0, 1177.0, 2568.0, 1785.0, 2124.0, 1625.0, 1392.0, 3298.0, 1510.0, 1207.0, 1294.0, 1001.0, 3864.0, 1588.0, 1742.0, 1591.0, 2226.0, 2826.0, 1540.0, 1823.0, 1247.0, 948.0, 1566.0, 1225.0, 2166.0, 1291.0, 1122.0, 1712.0, 2552.0, 2098.0, 933.0, 1390.0, 2993.0, 1910.0, 2708.0, 1194.0, 2558.0, 1818.0, 1691.0, 972.0, 1685.0, 1556.0, 2045.0, 1376.0, 1635.0, 2861.0, 1534.0, 1022.0, 2009.0, 1377.0, 3618.0, 1236.0, 2048.0, 2782.0, 2344.0, 2394.0, 1612.0, 1943.0, 1259.0, 1759.0, 2885.0, 1750.0, 1414.0, 1406.0, 2477.0, 1254.0, 1109.0, 1167.0, 2275.0, 1270.0, 1554.0, 1179.0, 1199.0, 1212.0, 2408.0, 2302.0, 3020.0, 1619.0, 1564.0, 1336.0, 1474.0, 15.0, 2509.0, 2747.0, 1115.0, 1342.0, 1315.0, 1072.0, 1812.0, 2595.0, 2249.0, 1633.0, 2118.0, 1736.0, 1902.0, 1282.0, 1.0, 1935.0, 980.0, 1571.0, 1041.0, 2123.0, 2300.0, 1637.0, 1308.0, 936.0]
Distinct values of total_bedrooms:  1848

Data Transformation

In [55]:
# using loop i calculate the reqd. value and add it to a list and then add a column to 'data' assigning it to the list
list2 = []
for i in range(0,17000):
  final = (data['total_bedrooms'][i]) / (data['total_rooms'][i])
  list2.append(final)

data['total_bedrooms_per_total_rooms'] = list2
data.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_bedrooms_per_total_rooms
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,0.228617
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,0.248497

In [56]:
# using describe to get a dataframe called summary which has all info and then extracting particular reqd. info from it
summary = data.describe()
print("Mean: ", summary['total_bedrooms_per_total_rooms']['mean'])
print("Standard Deviation: ", summary['total_bedrooms_per_total_rooms']['std'])

Mean:  0.21275998821034803
Standard Deviation:  0.057823008903161756

Data Filtering

In [57]:
# filtering those rows where median income is more than 5
dataset_1 = data[data['median_income']>5]
dataset_1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_bedrooms_per_total_rooms
32,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0,0.172535
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0,0.161077
92,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0,0.153194
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0,0.165998
100,-115.59,32.79,8.0,2183.0,307.0,1000.0,287.0,6.3814,159900.0,0.140632
...,...,...,...,...,...,...,...,...,...,...
16737,-122.89,38.38,16.0,2017.0,369.0,931.0,336.0,5.7664,267500.0,0.182945
16762,-122.94,38.57,33.0,1530.0,266.0,728.0,250.0,5.1005,266700.0,0.173856
16776,-123.00,38.33,8.0,3223.0,637.0,851.0,418.0,5.6445,364800.0,0.197642
16802,-123.17,39.18,14.0,2240.0,327.0,1030.0,308.0,5.9585,214900.0,0.145982
16899,-124.05,40.94,14.0,1452.0,217.0,516.0,181.0,5.0329,165600.0,0.149449

In [58]:
# filtering based on conditions -- usage of & is necessary, 'and' won't work as these are not boolean values
dataset_2 = data[(data['total_rooms']>10000) & (data['median_house_value']<150000)]
dataset_2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,total_bedrooms_per_total_rooms
133,-116.06,34.15,15.0,10377.0,2331.0,4507.0,1807.0,2.2466,66800.0,0.224631
191,-116.36,33.88,11.0,12557.0,3098.0,2453.0,1232.0,1.7844,78500.0,0.246715
198,-116.38,33.73,10.0,11836.0,2405.0,3811.0,1570.0,4.0079,134500.0,0.203194
201,-116.39,33.82,15.0,11115.0,2257.0,4122.0,1653.0,2.7219,74400.0,0.203059
229,-116.47,33.81,7.0,10105.0,2481.0,6274.0,2095.0,2.4497,90900.0,0.245522
...,...,...,...,...,...,...,...,...,...,...
12654,-121.75,38.67,9.0,12139.0,2640.0,6837.0,2358.0,3.1250,132500.0,0.217481
12772,-121.79,36.64,11.0,32627.0,6445.0,28566.0,6082.0,2.3087,118800.0,0.197536
13388,-121.94,38.27,35.0,10869.0,2226.0,9879.0,2152.0,2.5681,81300.0,0.204803
13707,-122.00,38.25,7.0,11768.0,1893.0,6657.0,1874.0,4.9222,142900.0,0.160860
15436,-122.31,40.55,11.0,13714.0,2302.0,6511.0,2267.0,3.5522,100100.0,0.167858

Export Modified Data

In [59]:
data.to_csv('modified_data.csv')

# **Part - 2**

Array Creation and Indexing

In [64]:
#1 Here I make a list via loop to contain all 20 integers and then make it a np array
import numpy as np
l = []
for i in range(1,21):
  l.append(i)
arr1 = np.array(l)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
#2 Here I use slicing with start, stop and a step of 2 to take alternative numbers  i.e. even nos.
arr2 = arr1[1:20:2]
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
#3 First I create an array of 20 elements as specified and then reshape it to 5 row, 4 column
arr3 = np.random.randint(10,101,20)
arr3_reshaped = arr3.reshape(5,4)
arr3_reshaped

array([[15, 85, 99, 57],
       [13, 91, 58, 84],
       [81, 92, 97, 35],
       [68, 40, 58, 38],
       [71, 38, 33, 68]])

In [67]:
#4 Used slicing to extract subarray
arr3_modified = arr3_reshaped[0:4, 0:2]
arr3_modified

array([[15, 85],
       [13, 91],
       [81, 92],
       [68, 40]])

Array Manipulation

In [68]:
#1
arr1_reshaped = arr1.reshape(4,5)
arr1_reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
#2
arr1_reshaped_converted = arr1_reshaped.flatten()
arr1_reshaped_converted

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
#3 Used the builtin function to perform matri multiplcation after generating a random matrix 5x1
arr4 = np.random.randint(10,31, 5)
arr4 = arr4.reshape(5,1)

#matrix multiplication
mul_matrix = np.matmul(arr1_reshaped, arr4)
mul_matrix

array([[ 258],
       [ 663],
       [1068],
       [1473]])

Boolean and Fancy Indexing

In [71]:
#1
arr = np.random.randint(0,101,10)
arr

array([ 14,  56,  70,  96,   1,  55, 100,   9,  31,  92])

In [72]:
#2 Created a mask (arr>50) and applied it on arr to extract elements greater than 50
arr_bool = arr[arr>50]
arr_bool

array([ 56,  70,  96,  55, 100,  92])

In [73]:
#3 Used fancy indexing to extract elements at index 0 and 3
fancy_index = [0,3]
arr_fancy = arr[fancy_index]
arr_fancy

array([14, 96])

Statistical Operations

In [74]:
arr3_reshaped

array([[15, 85, 99, 57],
       [13, 91, 58, 84],
       [81, 92, 97, 35],
       [68, 40, 58, 38],
       [71, 38, 33, 68]])

In [75]:
# I create lists to store data for each column, then just create a loop to select each column calculate the stats
# and just add it to the respective list. A mask is created for each column and then applied on each column to
# obtain the array of reqd. values and convert it to list and add the values in this list to a master list - 'empty_list'
# finally i print all these lists and the empty_list as an array
mean_list = []
max_list = []
sum_list = []
empty_list = []

for i in range(0,4):
  mean = arr3_reshaped[:,i].mean()
  max = arr3_reshaped[:,i].max()
  sum = arr3_reshaped[:,i].sum()

  mask = arr3_reshaped[:,i]>mean

  l = (arr3_reshaped[:,i][mask]).tolist()
  for j in range(0, len(l)):
    empty_list.append(l[j])

  mean_list.append(mean)
  max_list.append(max)
  sum_list.append(sum)

print(mean_list, max_list, sum_list)
print(np.array(empty_list))

[49.6, 69.2, 69.0, 56.4] [81, 92, 99, 84] [248, 346, 345, 282]
[81 68 71 85 91 92 99 97 57 84 68]

# **Part 3**

Loops and Conditional Statements

In [60]:
#1 using infinite running loop to get the fibonacci nos (by adding the last 2 elements of the list)
# with a break condition that if the number to be appended > 100 then break the loop
list = [0,1]

while True:
  n = len(list)
  if list[n-1]+list[n-2] > 100:
    break
  list.append(list[n-1]+list[n-2])


print(list)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [61]:
#2
for i in range(1,51):
  if i%3==0 and i%5==0:
    print("FizzBuzz", i)
  elif i%5==0:
    print("Buzz", i)
  elif i%3==0:
    print("Fizz", i)

Fizz 3
Buzz 5
Fizz 6
Fizz 9
Buzz 10
Fizz 12
FizzBuzz 15
Fizz 18
Buzz 20
Fizz 21
Fizz 24
Buzz 25
Fizz 27
FizzBuzz 30
Fizz 33
Buzz 35
Fizz 36
Fizz 39
Buzz 40
Fizz 42
FizzBuzz 45
Fizz 48
Buzz 50

Variable-Length Arguments

In [62]:
#1 and 2
l = []
n = int(input("How many numbers?: "))
for i in range(0,n):
  x = int(input("Enter number: "))
  l.append(x)

sum = 0
for i in l:
  sum  = sum + i


l.sort()
if n%2 == 0:
  print("Median: ", (l[(n-1)//2]+l[((n-1)//2)+1])/2)
else:
  print("Median: ", l[(n-1)//2])

print("Average of numbers: ", sum/n)

How many numbers?: 4
Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Median:  2.5
Average of numbers:  2.5

Error Handling

In [63]:
#1
n1 = float(input("Enter number 1: "))
n2 = float(input("Enter number 2: "))

try:
  division = n1/n2
except Exception as e:
  print("Error: ",e)
else:
  division = n1/n2
  print("Division: ", division)

Enter number 1: 4
Enter number 2: 0
Error:  float division by zero

# **Bonus Challenge**

In [78]:
#1 Generating a random 3d array
ar = np.random.randint(0,20,8)
ar_3d = ar.reshape(2,2,2)
ar_3d

array([[[ 8, 12],
        [18,  9]],

       [[12, 12],
        [14,  5]]])

In [83]:
#2 Swapping axes in 3d array (row and column swapped below, depth unchanged)
ar_3d.swapaxes(1,2)

array([[[ 8, 18],
        [12,  9]],

       [[12, 14],
        [12,  5]]])

In [84]:
#3 Finding sum of elements of array along a particular axis
np.sum(ar_3d, axis = 1)

array([[26, 21],
       [26, 17]])

In [89]:
#4 Adding a vector to 2d array
a = np.random.randint(0,20,(2,2))
w = [1,1]
sup = w + a
print(a)
print(sup)

[[19 13]
 [11 16]]
[[20 14]
 [12 17]]